version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: claude-grid
    main: .
    binary: claude-grid
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}

universal_binaries:
  - id: claude-grid
    replace: true

archives:
  - id: claude-grid
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.tar.gz"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - repository:
      owner: riricardoMa
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    
    homepage: https://github.com/riricardoMa/claude-grid
    
    description: "Spawn and tile multiple Claude Code instances in a grid layout"
    
    license: MIT
    
    test: |
      system "#{bin}/claude-grid", "version"
    
    install: |
      bin.install "claude-grid"
    
    caveats: |
      Requires Claude Code to be installed:
        npm install -g @anthropic-ai/claude-code
      
      For Warp backend support, install Warp:
        https://www.warp.dev
      
      First use with Warp requires Accessibility permission:
        System Settings → Privacy & Security → Accessibility
