version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: claude-grid
    main: .
    binary: claude-grid
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.CommitDate}}

universal_binaries:
  - id: claude-grid
    replace: true

archives:
  - id: claude-grid
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.tar.gz"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

# Homebrew tap placeholder (Task 17 will configure this)
# brews:
#   - repository:
#       owner: riricardoMa
#       name: homebrew-tap
